#!/usr/bin/env bash
# checking for command line argument
   
if [ $# -lt 4 ]
then    
        echo"usege: 0-transfer-file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 exit 1
 fi      
  
 # assigning paramentals to variables
 path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4
 
# deaseblering strick host key checking 
 
scp -o "stricthostkeycheking" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the transfer is successful
if [ $7 -eq 0]
then
      echo"file was transfered successfully"
else    
      echo"file transfer failed"
 fi
